# Generated by Django 5.2.3 on 2025-06-15 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.PositiveIntegerField(choices=[(1, '1-комнатная'), (2, '2-комнатная'), (3, '3-комнатная')], verbose_name='Количество комнат')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Площадь (м²)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена ($)')),
                ('layout_description', models.TextField(blank=True, verbose_name='Описание планировки')),
                ('main_image', models.ImageField(upload_to='apartment_types/', verbose_name='Главное фото')),
                ('layout_image', models.ImageField(blank=True, upload_to='apartment_types/layouts/', verbose_name='Планировка')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='Всего квартир этого типа')),
                ('available_count', models.PositiveIntegerField(default=0, verbose_name='Доступно для покупки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип квартиры',
                'verbose_name_plural': 'Типы квартир',
                'ordering': ['complex', 'rooms'],
            },
        ),
        migrations.CreateModel(
            name='ResidentialComplex',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='Название ЖК')),
                ('slug', models.SlugField(blank=True, max_length=220, primary_key=True, serialize=False, verbose_name='URL-адрес')),
                ('description', models.TextField(verbose_name='Описание ЖК')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('total_buildings', models.PositiveIntegerField(default=1, verbose_name='Количество домов')),
                ('total_floors', models.PositiveIntegerField(default=12, verbose_name='Этажность')),
                ('status', models.CharField(choices=[('planning', 'Планируется'), ('construction', 'Строится'), ('completed', 'Сдан')], default='construction', max_length=20, verbose_name='Статус')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('infrastructure', models.TextField(blank=True, help_text='Опишите инфраструктуру ЖК: парковка, детские площадки, магазины и т.д.', verbose_name='Инфраструктура')),
                ('main_image', models.ImageField(upload_to='complexes/', verbose_name='Главное фото ЖК')),
                ('location_2gis', models.URLField(blank=True, help_text='Вставьте ссылку на местоположение в 2GIS', verbose_name='Ссылка на 2GIS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Жилой комплекс',
                'verbose_name_plural': 'Жилые комплексы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartment_types/gallery/', verbose_name='Фото интерьера')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('room_name', models.CharField(blank=True, help_text='Гостиная, Спальня, Кухня, Ванная, Прихожая и т.д.', max_length=100, verbose_name='Какая комната')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок показа')),
                ('apartment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='elitka.apartmenttype', verbose_name='Тип квартиры')),
            ],
            options={
                'verbose_name': 'Фото интерьера',
                'verbose_name_plural': 'Фотографии интерьеров',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ComplexImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complexes/gallery/', verbose_name='Фотография')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок показа')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='elitka.residentialcomplex', verbose_name='Жилой комплекс')),
            ],
            options={
                'verbose_name': 'Фото ЖК',
                'verbose_name_plural': 'Фотографии ЖК',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='apartmenttype',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_types', to='elitka.residentialcomplex', verbose_name='Жилой комплекс'),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер квартиры')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('position', models.PositiveIntegerField(help_text='1,2,3,4,5,6 - позиция квартиры на этаже', verbose_name='Позиция на этаже')),
                ('status', models.CharField(choices=[('available', 'Свободна'), ('booked', 'Забронирована'), ('sold', 'Продана')], default='available', max_length=20, verbose_name='Статус')),
                ('is_corner', models.BooleanField(default=False, verbose_name='Угловая квартира')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP квартира')),
                ('view_direction', models.CharField(blank=True, help_text='Север, Юг, Восток, Запад', max_length=50, verbose_name='Сторона света')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Если не указана, берется цена из типа квартиры', max_digits=12, null=True, verbose_name='Индивидуальная цена ($)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('apartment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='elitka.apartmenttype', verbose_name='Тип квартиры')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['apartment_type__complex', 'floor', 'position'],
                'unique_together': {('apartment_type', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('apartment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='elitka.apartmenttype', verbose_name='Тип квартиры')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные квартиры',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'apartment_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='apartmenttype',
            unique_together={('complex', 'rooms')},
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 звезд'), (2, '2 звезд'), (3, '3 звезд'), (4, '4 звезд'), (5, '5 звезд')], default=5, verbose_name='Рейтинг')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен модератором')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='elitka.residentialcomplex', verbose_name='Жилой комплекс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'complex')},
            },
        ),
    ]
