# Generated by Django 5.2.3 on 2025-06-15 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elitka', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('pending', 'Новая заявка'), ('confirmed', 'Подтверждено'), ('completed', 'Сделка завершена'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена ($)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Ответ менеджера')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='elitka.apartment', verbose_name='Квартира')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Вопрос')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('answered', 'Отвечен'), ('closed', 'Закрыт')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('apartment', models.ForeignKey(blank=True, help_text='Конкретная квартира (если вопрос о ней)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='elitka.apartment', verbose_name='Квартира')),
                ('apartment_type', models.ForeignKey(blank=True, help_text='Тип квартиры (если вопрос общий)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='elitka.apartmenttype', verbose_name='Тип квартиры')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, задавший вопрос (если авторизован)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-created_at'],
            },
        ),
    ]
